# Generated by Django 3.2.6 on 2021-09-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_mycart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry', models.CharField(max_length=10)),
                ('balance', models.FloatField(default=50000)),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
    ]
